# Generated by Django 3.0.5 on 2020-04-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200405_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_active',
            new_name='inactive',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_active',
            new_name='inactive',
        ),
        migrations.AddField(
            model_name='category',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
