# Generated by Django 3.0.5 on 2020-05-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200510_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerhistory',
            name='question',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='historical_question', to='questions.Question'),
            preserve_default=False,
        ),
    ]
