# Generated by Django 3.0.5 on 2020-05-17 19:07

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_answerhistory_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(null=True, upload_to='question_files', validators=[questions.models.Question.validate_file_type, questions.models.Question.validate_file_size]),
        ),
    ]
