# Generated by Django 3.0.5 on 2020-05-18 15:01

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='question_files', validators=[questions.models.Question.validate_file_type, questions.models.Question.validate_file_size]),
        ),
    ]
